version: '2'
services:
  spring:
    container_name: spring
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-docker:17-alpine
    ports:
      - 8080:8090
    env_file:
      - .env
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge