name: Docker Image CI

on:
  push:
    branches: [ main ]       
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # setup Docker buld action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: run maven command
      run: mvn package
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./
        # Note: tags has to be all lower-case
        tags: |
          ismaeilshajar/spring-docker:17-alpine-latest 
          ghcr.io/ismaeil-shajar/spring-docker:17-alpine-latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
